name: manage-azure-policy-1ff29b62
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/LAB_-_Allowed_resource_types_5ca1125c-46cf-4db9-b9d4-3ae99b262bef/**'
#      - .github/workflows/manage-azure-policy-1ff29b62.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1ff29b62}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/LAB_-_Allowed_resource_types_5ca1125c-46cf-4db9-b9d4-3ae99b262bef/**
